/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Close By API
 * Nigeria's campus marketplace + Hush event platform
 * OpenAPI spec version: 1.0.0
 */
export interface ErrorResponse {
  error: string;
}

export interface Storefront {
  userId?: string;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  phone?: string | null;
  socialLinks?: string[];
}

export type ListingCategory = typeof ListingCategory[keyof typeof ListingCategory];


export const ListingCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export interface Listing {
  id: string;
  userId: string;
  title: string;
  /** @nullable */
  description?: string | null;
  category: ListingCategory;
  location: string;
  /** Price in kobo (₦ × 100) */
  price: number;
  /** @nullable */
  imageUrl?: string | null;
  createdAt: string;
  seller?: Storefront | null;
}

export type CreateListingInputCategory = typeof CreateListingInputCategory[keyof typeof CreateListingInputCategory];


export const CreateListingInputCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export interface CreateListingInput {
  /** @maxLength 200 */
  title: string;
  description?: string;
  category: CreateListingInputCategory;
  location: string;
  /** @minimum 0 */
  price: number;
  /** @nullable */
  imageUrl?: string | null;
}

export type HushEventStatus = typeof HushEventStatus[keyof typeof HushEventStatus];


export const HushEventStatus = {
  pending: 'pending',
  approved: 'approved',
} as const;

export interface HushEvent {
  id: string;
  organizerId: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  flyerUrl?: string | null;
  /** @nullable */
  paymentProofUrl?: string | null;
  bankName: string;
  accountNumber: string;
  accountName: string;
  /** Price in kobo */
  ticketPrice: number;
  eventDate: string;
  location: string;
  status: HushEventStatus;
  capacity: number;
  soldTickets?: number;
}

export interface CreateHushEventInput {
  /**
     * @minLength 3
     * @maxLength 200
     */
  title: string;
  description?: string;
  flyerUrl?: string;
  paymentProofUrl?: string;
  bankName: string;
  accountNumber: string;
  accountName: string;
  /** Price in kobo */
  ticketPrice: number;
  eventDate: string;
  location: string;
  capacity: number;
}

export type TicketReceiptTicket = {
  id?: string;
  eventId?: string;
  buyerId?: string;
  buyerName?: string;
  referenceCode?: string;
  createdAt?: string;
};

export interface TicketReceipt {
  ticket?: TicketReceiptTicket;
  event?: HushEvent;
}

export interface PaginatedListings {
  data?: Listing[];
  total?: number;
  page?: number;
}

export interface StorefrontWithListings {
  data?: Storefront | null;
  listings?: Listing[];
}

/**
 * Validation error
 */
export type BadRequestResponse = ErrorResponse;

/**
 * Missing or invalid token
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Insufficient role
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Resource not found
 */
export type NotFoundResponse = ErrorResponse;

export type GetHealth200 = {
  status?: string;
  timestamp?: string;
};

export type GetStats200 = {
  totalListings?: number;
  activeSellers?: number;
  supportedLocations?: number;
};

export type GetListingsParams = {
/**
 * Full-text search
 */
q?: string;
category?: GetListingsCategory;
location?: string;
minPrice?: number;
maxPrice?: number;
userId?: string;
page?: number;
limit?: number;
};

export type GetListingsCategory = typeof GetListingsCategory[keyof typeof GetListingsCategory];


export const GetListingsCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export type CreateListing201 = {
  data?: Listing;
};

export type GetListing200 = {
  data?: Listing;
};

export type UpdateListing200 = {
  data?: Listing;
};

export type UpsertStorefrontBody = {
  /** @maxLength 500 */
  bio?: string;
  /** @nullable */
  avatarUrl?: string | null;
  phone?: string;
  socialLinks?: string[];
};

export type UpsertStorefront200 = {
  data?: Storefront;
};

export type GetHushEvents200 = {
  data?: HushEvent[];
};

export type CreateHushEvent201 = {
  data?: HushEvent;
};

export type GetHushEvent200 = {
  data?: HushEvent;
};

export type ApproveHushEventParams = {
token: string;
};

export type BuyTicketBody = {
  eventId: string;
  /** @maxLength 100 */
  buyerName: string;
};

export type BuyTicket201 = {
  referenceCode?: string;
};

export type GetTicketReceipt200 = {
  data?: TicketReceipt;
};

