/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Close By API
 * Nigeria's campus marketplace — listings, storefronts, and Hush events
 * OpenAPI spec version: 1.0.0
 */
export interface ErrorResponse {
  error: string;
}

export type ListingCategory = typeof ListingCategory[keyof typeof ListingCategory];


export const ListingCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export interface SellerInfo {
  userId?: string;
  bio?: string | null;
  avatarUrl?: string | null;
  phone?: string | null;
  socialLinks?: string[];
}

export interface Listing {
  id: string;
  userId: string;
  title: string;
  description?: string | null;
  category: ListingCategory;
  location: string;
  /** Price in kobo (NGN × 100) */
  price: number;
  imageUrl?: string | null;
  createdAt: string;
  seller?: SellerInfo | null;
}

export interface Storefront {
  userId: string;
  bio?: string | null;
  avatarUrl?: string | null;
  phone?: string | null;
  socialLinks?: string[];
}

export type HushEventStatus = typeof HushEventStatus[keyof typeof HushEventStatus];


export const HushEventStatus = {
  pending: 'pending',
  approved: 'approved',
} as const;

export interface HushEvent {
  id: string;
  organizerId: string;
  title: string;
  description?: string | null;
  flyerUrl?: string | null;
  bankName: string;
  accountNumber: string;
  accountName: string;
  /** Price in kobo (NGN × 100) */
  ticketPrice: number;
  eventDate: string;
  location: string;
  status: HushEventStatus;
  capacity: number;
  /** Computed field — count of issued tickets */
  soldTickets: number;
}

export type TicketTicket = {
  id: string;
  buyerName: string;
  referenceCode: string;
  createdAt: string;
};

export type TicketEvent = {
  id: string;
  title: string;
  eventDate: string;
  location: string;
  ticketPrice: number;
  flyerUrl?: string | null;
};

export interface Ticket {
  ticket: TicketTicket;
  event: TicketEvent;
}

export interface ListingsPaginated {
  data: Listing[];
  total: number;
  page: number;
}

export interface StorefrontResponse {
  data: Storefront | null;
  listings: Listing[];
}

export type GetHealth200 = {
  status: string;
  timestamp: string;
};

export type GetStats200 = {
  totalListings: number;
  activeSellers: number;
  supportedLocations: number;
};

export type GetListingsParams = {
q?: string;
category?: string;
location?: string;
minPrice?: number;
maxPrice?: number;
userId?: string;
page?: number;
limit?: number;
};

export type CreateListingBodyCategory = typeof CreateListingBodyCategory[keyof typeof CreateListingBodyCategory];


export const CreateListingBodyCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export type CreateListingBody = {
  /** @maxLength 200 */
  title: string;
  description?: string;
  category: CreateListingBodyCategory;
  location: string;
  price: number;
  imageUrl?: string | null;
};

export type CreateListing201 = {
  data?: Listing;
};

export type GetListing200 = {
  data?: Listing;
};

export type UpdateListingBodyCategory = typeof UpdateListingBodyCategory[keyof typeof UpdateListingBodyCategory];


export const UpdateListingBodyCategory = {
  housing: 'housing',
  jobs: 'jobs',
  services: 'services',
  food_restaurants: 'food_restaurants',
  electronics: 'electronics',
  fashion: 'fashion',
  events: 'events',
} as const;

export type UpdateListingBody = {
  /** @maxLength 200 */
  title?: string;
  description?: string;
  category?: UpdateListingBodyCategory;
  location?: string;
  price?: number;
  imageUrl?: string | null;
};

export type UpdateListing200 = {
  data?: Listing;
};

export type UpsertStorefrontBody = {
  /** @maxLength 500 */
  bio?: string;
  avatarUrl?: string | null;
  phone?: string;
  socialLinks?: string[];
};

export type UpsertStorefront200 = {
  data?: Storefront;
};

export type GetHushEvents200 = {
  data?: HushEvent[];
};

export type CreateHushEventBody = {
  /** @maxLength 200 */
  title: string;
  description?: string;
  eventDate: string;
  location: string;
  /** @minimum 1 */
  capacity: number;
  /** @minimum 1 */
  ticketPrice: number;
  bankName: string;
  accountNumber: string;
  accountName: string;
  flyerUrl?: string;
  paymentProofUrl?: string;
};

export type CreateHushEvent201 = {
  data?: HushEvent;
};

export type GetHushEvent200 = {
  data?: HushEvent;
};

export type ApproveHushEventParams = {
token: string;
};

export type BuyTicketBody = {
  eventId: string;
  buyerName: string;
};

export type BuyTicket201 = {
  referenceCode: string;
};

export type GetTicket200 = {
  data?: Ticket;
};

