/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Close By API
 * Nigeria's campus marketplace + Hush event platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateListing201,
  CreateListingInput,
  ForbiddenResponse,
  GetListing200,
  GetListingsParams,
  NotFoundResponse,
  PaginatedListings,
  UnauthorizedResponse,
  UpdateListing200
} from './closeByAPI.schemas';






export type getListingsResponse200 = {
  data: PaginatedListings
  status: 200
}

export type getListingsResponseSuccess = (getListingsResponse200) & {
  headers: Headers;
};
;

export type getListingsResponse = (getListingsResponseSuccess)

export const getGetListingsUrl = (params?: GetListingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/listings?${stringifiedParams}` : `/listings`
}

/**
 * @summary List listings with optional filters
 */
export const getListings = async (params?: GetListingsParams, options?: RequestInit): Promise<getListingsResponse> => {

  const res = await fetch(getGetListingsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getListingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getListingsResponse
}





export const getGetListingsQueryKey = (params?: GetListingsParams,) => {
    return [
    `/listings`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetListingsQueryOptions = <TData = Awaited<ReturnType<typeof getListings>>, TError = unknown>(params?: GetListingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListingsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListings>>> = ({ signal }) => getListings(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListingsQueryResult = NonNullable<Awaited<ReturnType<typeof getListings>>>
export type GetListingsQueryError = unknown


export function useGetListings<TData = Awaited<ReturnType<typeof getListings>>, TError = unknown>(
 params: undefined |  GetListingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListings>>,
          TError,
          Awaited<ReturnType<typeof getListings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListings<TData = Awaited<ReturnType<typeof getListings>>, TError = unknown>(
 params?: GetListingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListings>>,
          TError,
          Awaited<ReturnType<typeof getListings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListings<TData = Awaited<ReturnType<typeof getListings>>, TError = unknown>(
 params?: GetListingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List listings with optional filters
 */

export function useGetListings<TData = Awaited<ReturnType<typeof getListings>>, TError = unknown>(
 params?: GetListingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createListingResponse201 = {
  data: CreateListing201
  status: 201
}

export type createListingResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createListingResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createListingResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createListingResponseSuccess = (createListingResponse201) & {
  headers: Headers;
};
export type createListingResponseError = (createListingResponse400 | createListingResponse401 | createListingResponse403) & {
  headers: Headers;
};

export type createListingResponse = (createListingResponseSuccess | createListingResponseError)

export const getCreateListingUrl = () => {




  return `/listings`
}

/**
 * @summary Create a listing (seller only)
 */
export const createListing = async (createListingInput: CreateListingInput, options?: RequestInit): Promise<createListingResponse> => {

  const res = await fetch(getCreateListingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createListingInput)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createListingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createListingResponse
}




export const getCreateListingMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListing>>, TError,{data: CreateListingInput}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createListing>>, TError,{data: CreateListingInput}, TContext> => {

const mutationKey = ['createListing'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createListing>>, {data: CreateListingInput}> = (props) => {
          const {data} = props ?? {};

          return  createListing(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateListingMutationResult = NonNullable<Awaited<ReturnType<typeof createListing>>>
    export type CreateListingMutationBody = CreateListingInput
    export type CreateListingMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse

    /**
 * @summary Create a listing (seller only)
 */
export const useCreateListing = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createListing>>, TError,{data: CreateListingInput}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createListing>>,
        TError,
        {data: CreateListingInput},
        TContext
      > => {
      return useMutation(getCreateListingMutationOptions(options), queryClient);
    }
    export type getListingResponse200 = {
  data: GetListing200
  status: 200
}

export type getListingResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getListingResponseSuccess = (getListingResponse200) & {
  headers: Headers;
};
export type getListingResponseError = (getListingResponse404) & {
  headers: Headers;
};

export type getListingResponse = (getListingResponseSuccess | getListingResponseError)

export const getGetListingUrl = (id: string,) => {




  return `/listings/${id}`
}

/**
 * @summary Get a single listing with seller info
 */
export const getListing = async (id: string, options?: RequestInit): Promise<getListingResponse> => {

  const res = await fetch(getGetListingUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getListingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getListingResponse
}





export const getGetListingQueryKey = (id: string,) => {
    return [
    `/listings/${id}`
    ] as const;
    }


export const getGetListingQueryOptions = <TData = Awaited<ReturnType<typeof getListing>>, TError = NotFoundResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListingQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListing>>> = ({ signal }) => getListing(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListingQueryResult = NonNullable<Awaited<ReturnType<typeof getListing>>>
export type GetListingQueryError = NotFoundResponse


export function useGetListing<TData = Awaited<ReturnType<typeof getListing>>, TError = NotFoundResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListing>>,
          TError,
          Awaited<ReturnType<typeof getListing>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListing<TData = Awaited<ReturnType<typeof getListing>>, TError = NotFoundResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListing>>,
          TError,
          Awaited<ReturnType<typeof getListing>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListing<TData = Awaited<ReturnType<typeof getListing>>, TError = NotFoundResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single listing with seller info
 */

export function useGetListing<TData = Awaited<ReturnType<typeof getListing>>, TError = NotFoundResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListing>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListingQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateListingResponse200 = {
  data: UpdateListing200
  status: 200
}

export type updateListingResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateListingResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateListingResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateListingResponseSuccess = (updateListingResponse200) & {
  headers: Headers;
};
export type updateListingResponseError = (updateListingResponse401 | updateListingResponse403 | updateListingResponse404) & {
  headers: Headers;
};

export type updateListingResponse = (updateListingResponseSuccess | updateListingResponseError)

export const getUpdateListingUrl = (id: string,) => {




  return `/listings/${id}`
}

/**
 * @summary Update a listing (owner only)
 */
export const updateListing = async (id: string,
    createListingInput: CreateListingInput, options?: RequestInit): Promise<updateListingResponse> => {

  const res = await fetch(getUpdateListingUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createListingInput)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateListingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateListingResponse
}




export const getUpdateListingMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListing>>, TError,{id: string;data: CreateListingInput}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateListing>>, TError,{id: string;data: CreateListingInput}, TContext> => {

const mutationKey = ['updateListing'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateListing>>, {id: string;data: CreateListingInput}> = (props) => {
          const {id,data} = props ?? {};

          return  updateListing(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateListingMutationResult = NonNullable<Awaited<ReturnType<typeof updateListing>>>
    export type UpdateListingMutationBody = CreateListingInput
    export type UpdateListingMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse

    /**
 * @summary Update a listing (owner only)
 */
export const useUpdateListing = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateListing>>, TError,{id: string;data: CreateListingInput}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateListing>>,
        TError,
        {id: string;data: CreateListingInput},
        TContext
      > => {
      return useMutation(getUpdateListingMutationOptions(options), queryClient);
    }
    export type deleteListingResponse204 = {
  data: void
  status: 204
}

export type deleteListingResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteListingResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteListingResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteListingResponseSuccess = (deleteListingResponse204) & {
  headers: Headers;
};
export type deleteListingResponseError = (deleteListingResponse401 | deleteListingResponse403 | deleteListingResponse404) & {
  headers: Headers;
};

export type deleteListingResponse = (deleteListingResponseSuccess | deleteListingResponseError)

export const getDeleteListingUrl = (id: string,) => {




  return `/listings/${id}`
}

/**
 * @summary Delete a listing (owner only)
 */
export const deleteListing = async (id: string, options?: RequestInit): Promise<deleteListingResponse> => {

  const res = await fetch(getDeleteListingUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteListingResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteListingResponse
}




export const getDeleteListingMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListing>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteListing>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteListing'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListing>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteListing(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteListingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListing>>>

    export type DeleteListingMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse

    /**
 * @summary Delete a listing (owner only)
 */
export const useDeleteListing = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListing>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListing>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteListingMutationOptions(options), queryClient);
    }
