/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Close By API
 * Nigeria's campus marketplace — listings, storefronts, and Hush events
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  StorefrontResponse,
  UpsertStorefront200,
  UpsertStorefrontBody,
} from "./closeByAPI.schemas";

export type getStorefrontResponse200 = {
  data: StorefrontResponse;
  status: 200;
};

export type getStorefrontResponseSuccess = getStorefrontResponse200 & {
  headers: Headers;
};
export type getStorefrontResponse = getStorefrontResponseSuccess;

export const getGetStorefrontUrl = (userId: string) => {
  return `/storefronts/${userId}`;
};

/**
 * @summary Get storefront + listings for a seller
 */
export const getStorefront = async (
  userId: string,
  options?: RequestInit,
): Promise<getStorefrontResponse> => {
  const res = await fetch(getGetStorefrontUrl(userId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getStorefrontResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getStorefrontResponse;
};

export const getGetStorefrontQueryKey = (userId: string) => {
  return [`/storefronts/${userId}`] as const;
};

export const getGetStorefrontQueryOptions = <
  TData = Awaited<ReturnType<typeof getStorefront>>,
  TError = unknown,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStorefront>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStorefrontQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStorefront>>> = ({
    signal,
  }) => getStorefront(userId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStorefront>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStorefrontQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStorefront>>
>;
export type GetStorefrontQueryError = unknown;

/**
 * @summary Get storefront + listings for a seller
 */

export function useGetStorefront<
  TData = Awaited<ReturnType<typeof getStorefront>>,
  TError = unknown,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getStorefront>>,
      TError,
      TData
    >;
    fetch?: RequestInit;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStorefrontQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type upsertStorefrontResponse200 = {
  data: UpsertStorefront200;
  status: 200;
};

export type upsertStorefrontResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type upsertStorefrontResponseSuccess = upsertStorefrontResponse200 & {
  headers: Headers;
};
export type upsertStorefrontResponseError = upsertStorefrontResponse401 & {
  headers: Headers;
};

export type upsertStorefrontResponse =
  | upsertStorefrontResponseSuccess
  | upsertStorefrontResponseError;

export const getUpsertStorefrontUrl = () => {
  return `/storefronts/me`;
};

/**
 * @summary Upsert authenticated user's storefront
 */
export const upsertStorefront = async (
  upsertStorefrontBody: UpsertStorefrontBody,
  options?: RequestInit,
): Promise<upsertStorefrontResponse> => {
  const res = await fetch(getUpsertStorefrontUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertStorefrontBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: upsertStorefrontResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as upsertStorefrontResponse;
};

export const getUpsertStorefrontMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upsertStorefront>>,
    TError,
    { data: UpsertStorefrontBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upsertStorefront>>,
  TError,
  { data: UpsertStorefrontBody },
  TContext
> => {
  const mutationKey = ["upsertStorefront"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upsertStorefront>>,
    { data: UpsertStorefrontBody }
  > = (props) => {
    const { data } = props ?? {};

    return upsertStorefront(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpsertStorefrontMutationResult = NonNullable<
  Awaited<ReturnType<typeof upsertStorefront>>
>;
export type UpsertStorefrontMutationBody = UpsertStorefrontBody;
export type UpsertStorefrontMutationError = ErrorResponse;

/**
 * @summary Upsert authenticated user's storefront
 */
export const useUpsertStorefront = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upsertStorefront>>,
    TError,
    { data: UpsertStorefrontBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof upsertStorefront>>,
  TError,
  { data: UpsertStorefrontBody },
  TContext
> => {
  return useMutation(getUpsertStorefrontMutationOptions(options));
};
